Examen 2
utn-app-movil/examenII pull request #15
Opened 2024-12-06 02:56 UTC by XxKeyDarkxX

Arreglar conflictos

2024-12-06 22:52 UTC, XxKeyDarkxX commented
@ebarahonautn  profe ya arregle conflictos que al tanto para que haga la revision

2024-12-07 02:49 UTC, ebarahonautn requested changes
arregle los comentarios indicados

2024-12-07 02:49 UTC, ebarahonautn commented on app/src/main/AndroidManifest.xml
está mal el manifest, agarre lo que esta en el manifest de main, lo pega y despues agrega lo suyo

2024-12-07 02:49 UTC, ebarahonautn commented on app/src/main/java/interfaces/APIService.kt
esta malo la union con lo de main puso una interfaz dentro de otra interfaz

2024-12-07 02:49 UTC, ebarahonautn commented on app/src/main/res/values/strings.xml
esta mal la union con lo del main, hay dos </resources> y no es correcto

2024-12-07 12:31 UTC, ebarahonautn approved these changes

2024-12-07 12:31 UTC, merged